### ISSUE TITLE
Feature request: Any plans for WebP support?

### ISSUE THREAD

**Issue by EzequielBruni** [zelon88/HRConvert2#13]
Basically just that. Though I wouldn't say no to the ability to automatically store specific kinds of converted files on the drive automatically. (I work with video a lot.)

**Comment by zelon88** [comment]
Thanks for taking the time to submit a feature request.

The ability to convert files to and from .webp files is included in v2.7.1 (9f0c9ba7d4557cc257c6a114b18319701dd12f5e). Other newly supported file formats include;

1. CRW
2. CIN
3. DCR
4. DDS
5. DIB
6. FLIF
7. GPLT
8. NEF
9. ORF
10. ORA
11. SCT
12. SFW
13. XCF
14. XWD
15. AVIF
16. ICO

As for your request to be able to store converted files on the server, this is a good concept and one that I had actually developed a solution for before HRConvert2 was around. Take a look at [HRCloud2](https://github.com/zelon88/HRCloud2). It contains the same conversion engine as HRConvert2 but it also adds user based Cloud drive features as well. It does take a bit more to setup, so keep an eye on [HRCloud3](https://github.com/zelon88/HRCloud3) which is probably about a year or so away from a beta version.

**Comment by zelon88** [comment]
AI was thinking about your secondary request a little bit more. This can be accomplished by adding two functional lines of code to the convertCore.php file. Specifically, we would need to add the same line of code twice, as there are two cleanup routines. Depending on where you want your permanent copies stored you could get away with only adding one line of code. The line of code is;

`if (!is_dir($DFilePath)) if (in_array(pathinfo($DFilePath, PATHINFO_EXTENSION), $VideoArray)) continue;`

If you want to store your permanent copies in /var/www/html/HRProprietary/HRConvert2/DATA then add this special line of code directly underneath the line `$DFilePath = $ConvertTemp.DIRECTORY_SEPARATOR.$DFile;`

If you want to store your permanent copies in the _$ConvertLoc_ specified in config.php then add this special line of code directly underneath the line `$DFilePath = $ConvertLoc.DIRECTORY_SEPARATOR.$DFile;`

If you want to store permanent copies in both places, then place the special line of code in both places.

The fully adjusted code block, with both permanent locations added, will look like this (Note that I have surrounded ;

`// / -----------------------------------------------------------------------------------
// / The following code cleans up old files.
if (file_exists($ConvertTemp)) { 
  $DFiles = array_diff(scandir($ConvertTemp), array('..', '.'));
  $now = time();
  foreach ($DFiles as $DFile) { 
    if (in_array($DFile, $DefaultApps)) continue;
    $DFilePath = $ConvertTemp.DIRECTORY_SEPARATOR.$DFile;
    echo $ConvertTemp;
    **if (!is_dir($DFilePath)) if (in_array(pathinfo($DFilePath, PATHINFO_EXTENSION), $VideoArray)) continue;**
    if ($DFilePath == $ConvertTemp.'/index.html') continue; 
    if ($now - fileTime($DFilePath) > ($Delete_Threshold * 60)) {
      if (is_dir($DFilePath)) { 
        @chmod ($DFilePath, 0755);
        cleanFiles($DFilePath);
        if (is_dir_empty($DFilePath)) @rmdir($DFilePath); } } } }
if (file_exists($ConvertLoc)) { 
  $DFiles = array_diff(scandir($ConvertLoc), array('..', '.'));
  $now = time();
  foreach ($DFiles as $DFile) { 
    if (in_array($DFile, $DefaultApps)) continue;
    $DFilePath = $ConvertLoc.DIRECTORY_SEPARATOR.$DFile;
    **if (!is_dir($DFilePath)) if (in_array(pathinfo($DFilePath, PATHINFO_EXTENSION), $VideoArray)) continue;**
    if ($now - fileTime($DFilePath) > ($Delete_Threshold * 60)) {
      if (is_dir($DFilePath)) { 
        @chmod ($DFilePath, 0755);
        cleanFiles($DFilePath); 
        if (is_dir_empty($DFilePath)) @rmdir($DFilePath); } } } }
// / -----------------------------------------------------------------------------------`

Note that I have placed bold around the special lines of code we added. If you do add these to your installation you obviously won't have the option of making them bold, so I recommend using some comments to separate out this modification.

`    // / -------------------------
    // / Custom code for excluding certain filetypes from cleanup routine.
    if (!is_dir($DFilePath)) if (in_array(pathinfo($DFilePath, PATHINFO_EXTENSION), $VideoArray)) continue;
    // / -------------------------`

Also note that this code is specific to Video files, as you said you would like to store those. If we change _$VideoArray_. If we were going to save documents, we would want to specify the _$DocumentArray_ instead. Scroll up a bit in convertCore.php to see which arrays are defined and what extensions they contain.

If you wanted to move these files somewhere else instead of leaving them in either directory we could do something like;

`if (!is_dir($DFilePath)) if (in_array(pathinfo($DFilePath, PATHINFO_EXTENSION), $VideoArray)) if (!file_exists($CustomLocation.DIRECTORY_SEPARATOR.$DFile)) copy($DFilePath, $CustomLocation.DIRECTORY_SEPARATOR.$DFile);`

Note that you would only need to add this special line of code once. Then add a line in config.php to define _$CustomLocation_. 

`  // / Custom location for storing permanent files. 
  // / DO NOT include a trailing slash.
$CustomLocation = '/path/to/your/custom/location';`

Just make sure that $CustomLocation exists and that the www-data user has read/write permissions in it.

Note that in all of these special lines of code we've developed we're doing a couple of things. We are checking if the file HRConvert2 is working on is a directory, because if it is then _PATHINFO_EXTENSION_ would throw an error. In the later code samples we're also checking that a file does not already exist in the _$CustomLocation_. If it did and we tried to write another one then _copy_ would throw an error.

**Comment by EzequielBruni** [comment]
@zelon88 Thanks for all the responses and help! Good to know WebP is already working. I don't need a full cloud platform at present, but in my home office I have two PCs, right? One where I do my work and gaming, and one that acts as a server/records video and audio from my first PC.

So I'm thinking that I could install the converter on my server-ish PC, and just have it automatically store files I convert. And well, with everything you just wrote, I think that might well be possible. Could probably even make it work in a (privileged) LXD container and mount the relevant data directories as storage in the container...

A project to consider. (He said, adding it to an ever-growing and increasingly impractical list.)
