### ISSUE TITLE
heic support?

### ISSUE THREAD

**Issue by bleomycin** [zelon88/HRConvert2#17]
Is this possible? Apple devices default to this format for years now.

**Comment by zelon88** [comment]
It's not impossible, but it's not a straightforward conversion.

I initially tried to look for a way to do the conversion with ffmpeg, figuring that heic is more like video than an image. https://trac.ffmpeg.org/ticket/6521

But it turns out heic is just a container for multiple heif. So the proper tool is ImageMagick. But ImageMagic can't do this without libheif and libheif265 baked into it at compile time. which is a lot of work to add to the install process. Upgrading an existing install to this hypothetical version would require a special procedure for uninstalling ImageMagick and rebuilding it from source. Maybe this would be the opportune time to create a full set of install/upgrade scripts?
https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

Either way, it is a big market so we should try to capture it. Let me mull over the options for a little bit...

**Comment by zelon88** [comment]
I just did some playing around with this, and it looks like if you follow our installation instructions that ImageMagick can do this out of the box. 

HRConvert2 v3.1.1 will take advantage of these improvements to ImageMagick to add support for Heic files in English and vastly improve support for image files in any language. v3.2 will extend support for all languages.

Running `convert -list format` will  show you a list of all the formats your ImageMagick supports. If HEIC conversions don't work I suggest an update or reinstall to the latest version of ImageMagick
