### ISSUE TITLE
Create official Docker image

### ISSUE THREAD

**Issue by whalehub** [zelon88/HRConvert2#2]
It would be neat if you could create a Docker image for HRConvert2 and push it to the Docker Hub so that people can seamlessly integrate it into their existing software stack.

**Comment by dwaaan** [comment]
https://github.com/dwaaan/HRConvert2-Docker

**Comment by zelon88** [comment]
I am so grateful for this!

Thank you so much!!! I'll link to the dockerized version in the README later tonight.

You are DA MAN!

**Comment by whalehub** [comment]
@dwaaan Thank you!

**Comment by zelon88** [comment]
Hey @Whalehub! I know it's been a long time since you created this issue, but I wanted you to know that due to changes in the [HonestRepair Alternative Licensing Policy])https://www.honestrepair.net/index.php/alternative-licensing) you get a free [BSD 3-Clause License](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)) for HRConvert2 for life. Thanks for your contribution to HonestRepair open-source software,

Also I'd like to grab the attention of @dwaaan. Because of your significant contributions to HonestRepair open-source software, please enjoy a free MIT license for HRConvert2, HRCloud2, & HRScan2. Thanks again!
