### ISSUE TITLE
Server reqa for 1k online user?

### ISSUE THREAD

**Issue by web-apply** [zelon88/HRConvert2#20]
Hi, @zelon88 
will this code handle 1k online file converter user?  I didn't go through the code, is there a job queue queue?  And how powerful a server is required for at least 1k online?

**Comment by zelon88** [comment]
That is a good question! 

**Running 1,000 Users on A Single Bare Metal Server**
- CPU:  One 8 Core CPU Minimum (Two 8+ Core CPU Recommended) 
- RAM:  64GB of RAM Minimum (128GB of RAM Recommended)
- Network:  10GbE
- Storage:  
- - OS:  256GB of SSD Storage in Software RAID 0 Minimum for "OS, Applications, Logs" Minimum (512GB in Hardware RAID 0 Recommended).
- - Data:  1TB of SSD Storage in Hardware RAID 10 for "User Data" Minimum (2TB in Hardware RAID 10 Recommended).
- Optional Storage:
- - Backups:  512GB - 1TB in RAID 5 Recommended (for backing up logs and/or system images).
- - System: 256GB - 512GB in RAID 0 Recommended (for dividing the OS drive & vastly increasing virtual memory). 
- Notes:  You will need to have an internet connection with substantial upload bandwidth. 1GBPS up would give each user 125 KBPS down.

**Running 1,000 Users on Several Bare Metal Servers**
- Step 1:  Setup 10 modestly sized bare metal servers.
- Step 2:  Setup a reverse proxy server at yourwebsite<dot>com.
- Step 3:  Have the reverse proxy identify the coarse location of the user using PHP and a local of the IP2Location database. The course location doesn't have to be accurate, it just needs to be unique.
- Step 4:  Redirect the user to a server unique to their coarse location. The server doesn't actually have to be near the user. You can have all the servers located in the same room with the same internet connection if you want. Example: us1.yourwebsite>dot>com, us2.yourwebsite<dot>com, eu1.yourwebsite<dot>com, ect... 
- Step 5:  You can now fine tune the workload among several servers that are less expensive to operate.
- Notes:  If all the servers are in the same location, you will need to have an internet connection with substantial upload bandwidth. 1GBPS up would give each user 125 KBPS down.

**Running 1,000 Users on Virtual Servers**
- Step 1:  Setup a VM hypervisor server with about as much power as what is listed in the "*Running 1,000 Users on A Single Bare Metal Server*" section.
- Step 2:  Create one server with modest compute resources and set it up 90% of the way. 
- Step 3:  Clone the first server you made with one server representing a different geographic location that you want to isolate. 
- Step 4:  Change the hostname and network details of the cloned servers and build your network as you see fit.
- Step 5:  From here you can follow the steps for "*Running 1,000 Users on Several Bare Metal Servers*" but skip Step 1.
- Notes:  You will need to have an internet connection with substantial upload bandwidth. 1GBPS up would give each user 125 KBPS down.

**From an application standpoint,** 

If you have 1000 users and each user is uploading 100mb up and 100mb down and you have virus scanning enabled, you are going to write each user upload a minimum of 2 times and read it a minimum of 3 times (if you have virus scanning enabled). If 1000 users each upload and download 100mb in 1 minute, you will need to sustain 5gb/s combined r/w speed. Of course some files are going to be 100kb and others are going to be 1.1gb... unless you put a limit on file upload size in the php.ini file.

As far as running multiple conversions at once, it depends entirely on the conversions being performed. HRConvert2 has a mechanism that attempts every conversion up to 5 times. These happen in a split second, but you could add a small pause to each conversion attempt to give the server time to catch up before trying again.

**Document Conversions**
Unoconv has its own job queue, so document conversions using Unoconv will come out one at a time. This is because of the way the LibreOffice API works, and how Unoconv uses it. More information is available here: https://github.com/unoconv/unoconv/issues/172

**Image Conversions**
For image conversions with ImageMagick you can run multiple conversions at once, but it would be beneficial to modify the code that calls ImageMagick to include `-limit memory 2GiB -limit map 2GiB` so you don't run out of memory. If you used this setting on a server with 64gb of available RAM then I would think that you could safely run 32 image conversions at the same time. If you limit the RAM to 512MiB instead this would give you 128 image conversions. But you would want to leave some resources for other conversions as well.

**Compression operations**
As I learned while making https://github.com/zelon88/xPress file compression and decompression performance is largely based on available memory resources. In general it will take about 8-10 times more memory to efficiently compress a file than it will to decompress that file. You can hardcode the calls to 7z so that you limit the dictionary size, which will in turn make compression operations consume less RAM at the expense of swap space. 

**Drawing, 3D Model Conversions, PDF, Audio, & Video Conversions**
You can expect these operations to use about 500mb-1gb for each instance that is running. These programs should all be fairly comfortable using virtual memory if they have to.
