### ISSUE TITLE
`rar` package unavailable on ARM

### ISSUE THREAD

**Issue by schklom** [zelon88/HRConvert2#27]
The `rar` package is not available for ARM processors on Ubuntu (source https://packages.ubuntu.com/search?keywords=rar&searchon=names&suite=all&section=all). In fact, it is only available for AMD64.
Would you switch to a different and more available RAR archiver, such as `7zip` or `p7zip`?

**Comment by zelon88** [comment]
Hello,

Thanks for supporting HRConvert2 with your suggestion.

Unless something has changed recently, I don't think that 7zip or P7zip can create rar archives due to license restrictions with the .rar file format. It is my understanding that, technically, the only legal way to create a RAR archive is with a Rar/WinRAR product license.

I don't have a test bed for this, but I would recommend playing around with https://github.com/ilteoood/rar-on-arm. If you can get that running, you could try replacing the...

`if (in_array($extension, $arrayraro)) $returnData = shell_exec('rar a -ep1 -r '.$newPathname.' '.$safedir2);`

...line of convertCore.php with something like...

`if (in_array($extension, $arrayraro)) $returnData = shell_exec('docker run ilteoood/rar-on-arm a -ep1 -r '.$newPathname.' '.$safedir2);`

Feel free to let me know if you need additional guidance.

**Comment by bit-man** [comment]
Just for anyone looking for amd64 image (and probably other architectures) take a look at [how was solved](https://github.com/dwaaan/HRConvert2-Docker/pull/10#issuecomment-1874874114) during image creation with no php code modification. Also there's an [available image for release 3.1](https://github.com/dwaaan/HRConvert2-Docker/pull/10#issuecomment-1874875339) (linux/amd64 and linux/arm64)

Enjoy!
