### ISSUE TITLE
Converter is not working

### ISSUE THREAD

**Issue by AdamsLegacyHD** [zelon88/HRConvert2#33]
Hi, 
This may be user error however when I try to convert a file it downlosts as a .htm file stating it failed. 
I see nothing in the logs. 

Has anyone come across this before?

Please see below :

![image](https://user-images.githubusercontent.com/32718428/216594374-4c240ebf-a648-4dc5-b695-837683f0efc5.png)

**Comment by AdamsLegacyHD** [comment]
I lied - I obviously did not know how to read a log file.

I found this -

 bf226aa3b823/ac97488c703a: The file /var/www/html/HRProprietary/HRConvert2/DATA/bf226aa3b823/ac97488c703a/UbuntuServerCLIprotips190422.jpg failed second stage validation!

**Comment by zelon88** [comment]
It is interesting that it tries to download a .htm file.

Can you tell me the version you are running? You can find this information in the versionInfo.php file.
Also can you provide more log files?

**Comment by HenryBspoke** [comment]
I am experienced the same issue currently - the version I am running is: v3.2.9

The antivirus scans and compression work fine, this only happens when using OCR Method 1 & 2 but also with any file conversions that I try to do. PDF -> Text produces HTML but PDF -> DocX will attempt to download a DocX (both though will still fail but it's allocating the correct file types in it's attempt). It's the same second stage validation issue each time resulting in the files not downloading or being locatable on the server. 

If I look in the directories it's pointed to I can see the original file is in there fine but the newly generated file is nowhere to be seen - due to it uploading the file into that directory fine I assume the issue isn't one of a permissions problem. 

Appreciate your help, happy to work together to resolve the error. -H

**Comment by zelon88** [comment]
Is this still happening in the latest version?
Also, are you installing on bare-metal or using Docker?
