### ISSUE TITLE
Some typos in sanitizeCore.php

### ISSUE THREAD

**Issue by robre** [zelon88/HRConvert2#4]
I noticed that there are some typos in sanitizeCore.php - I am too lazy to create a pull request.
line 96 - 'sstr_replace' and 'tr_replace' are used instead of 'str_replace'
also I suspect in line 95 maybe you meant filestodownload instead of upload?

best regards

**Comment by zelon88** [comment]
You are absolutely correct! I'm sorry for these mistakes and I appreciate you bringing my attention to them. I am away from my desk at the moment, but I've fixed the code in question in commit 8e67e3290e40728c81ff5bcc667bb3119715b437. Specifically lines 95 & 96 of sanitizeCore.php. I will make time in the very near future to do a thorough review of this code. Thanks again.

Because you took the time to report an issue (_and a very concise correction for it_), and in accordance with the HonestRepair Alternative Licensing Policy; please enjoy a BSD 3-Clause License for HRConvert2 for life. Thanks for contributing to HonestRepair open-source software!
