### ISSUE TITLE
SVG to... does nothing

### ISSUE THREAD

**Issue by JFPCreations** [zelon88/HRConvert2#49]
I tried SVG to PNG or JPG and it did nothing. The ring is turning and nothing happen.

PNG to JPG or WebP worked flawlessly.

Thank you.

**Comment by zelon88** [comment]
Hello, sorry to hear.
Can you share logs from the failed conversion?

Also, in a terminal, what is the output of......


`convert -version`


Also, what is the output of.....

`magick -version`



I suspect you are using ImageMagick version 7 or later. HRConvert2 v2.9.9 and earlier uses ImageMagick version 6.
I will begin working on a mechanism to determine the convert version, and adjust the logic of HRConvert2 accordingly.

The problem is because in version 6 the command to convert an image was....
`convert`
.....and in version 7 the command is now.....
`magick convert`

So we can make some logic to determine the version of ImageMagick that is installed on the server, and then adjust the internal conversion commands accordingly. 

I'm 99% sure that's going to be your problem, but log files and the output of those two commands will tell me for certain.

**Comment by zelon88** [comment]
Can you try the latest version and tell me what happens?

I did some playing around with this and I suspect if you try to run this on a newer version of HRConvert2 that the file would be detected as a drawing file instead of an image file like you describe.
