### ISSUE TITLE
Docker image missing rar command

### ISSUE THREAD

**Issue by bit-man** [zelon88/HRConvert2#60]
Using image zelon88/hrconvert2:v3.3.2 for amd64 fails to archive text file

1. Upload text file
2. Press Continue...
3. Select archive in rar format
4. Press Archive file
5. No file is downloaded

At JavaScript console access to http://host:port/HRProprietary/HRConvert2/DATA/11a8d2f80075/54a3d2c7e06a/input.rar returns 404 (Not Found) 

At docker log the next message is shown

```
sh: 1: rar: not found
```

**Comment by zelon88** [comment]
Thanks! Looking into this.

Technically rar and unrar are non-free. Maybe we try 7z instead, or maybe we have a config.php entry to specify an $RARArchiveMethod, either 7z or rar. I'll have to experiment.

**Comment by zelon88** [comment]
So 7z still can't create rar archives and probably never will because of licensing. I feel like every couple years I have to fall back into this rarlab licensing hell hole in order to re-realize how terrible proprietary software is.

The next release of the core will include logic for setting an alternate program for .rar files. This is mostly for development purposes, as it will make testing easier in the future. Currently it's setup so that I can test 7z, but this doesn't work and won't work.

 I think we need to just find a way to get rar onto the docker image somehow.

**Comment by bit-man** [comment]
Tried to add rar to Dockerfile and docker build throws this error :

```
Package rar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'rar' has no installation candidate
The command '/bin/sh -c apt-get install -y git python3 zip unzip rar' returned a non-zero code: 100
```

Looking at `/etc/apt/` files seems that the apt sources have been tweaked and apt doesn't know where to find rar/unrar. I'll try to look at it during the weekend

**Comment by bit-man** [comment]
As suspected the apt configuration has no entry for some sources, in this case `non-free`

**Comment by zelon88** [comment]
This didn't work out of the box for me, but it was very close.
I tweaked it a bit and it seems to work now.

Thanks again! I'll be sure to mention your contribution in the release notes for v3.3.3.
