### ISSUE TITLE
ERROR!!! HRConvert2-3: Could not set the execution timer!

### ISSUE THREAD

**Issue by techdash** [zelon88/HRConvert2#69]
I am getting this error after installing it on my live server. I changed php.ini settings but still the error is coming! I have a VPS with Ubuntu 22 and PhP 8.1.2 .

**Comment by zelon88** [comment]
I honestly have no recourse for that. 

The execution timer ensures that scripts do not run indefinatly. If they did, due to some crash or error, the hanging processes on the server could quickly cosume all available resources on the server and effectively DDOS the server. The execution timer is a function of Apache2 that prevents a faulty PHP script from running forever.

Resetting the execution timer is the first thing HRConvert2 does. It does this because if it has been called by another application using the require() or include() functions then those previous applications would have consumed a portion of the available HRConvert2's execution time.

Possible reasons include;

1. PHP is in safe mode. To fix this, run  'sudo featherpad /etc/php/8.0/apache2/php.ini' and then search the file for..... `safe_mode` and make sure that it is set to Off. Then run 'sudo service apache2 restart' to restart Apache and have the change take effect.

2. You may have forgotten to reboot the computer, or restart apache after installing HRConvert2. To fix this, run 'sudo service apache2 restart'

3. Actual corruption, as suggested by Documentation\ERROR_DESCRIPTIONS.php. This is a very unusual error to have. Make sure your whole stack is up to date.

Please give the proposed solutions in section 1 and 2 a shot, and let me know the result.

If all else fails you can just open convertCore.php and comment out the following line.....
`if (!$TimeReset) die('ERROR!!! HRConvert2-3: Could not set the execution timer!');`

To comment out this line, add [//](url) in front at the beginning.
